### ISSUE TITLE
TPError: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by tenetk2019** [ZephrFish/GoogD0rker#10]
iam receiving this error an execute -d xxxx.com

**Comment by ZephrFish** [comment]
do you have any more info on this?

**Comment by BonJarber** [comment]
Hit this same issue today. Ran the tool for the first time on a domain and while on `Finding FIND DOCUMENTS BY EXTENSION` it threw a stack trace with `urllib.error.HTTPError: HTTP Error 429: Too Many Requests`. Subsequent runs of the tool immediately error out with the same stack trace.

```
$: python3 googd0rker.py -d example.com
Finding Login Pages for example.com

Traceback (most recent call last):
  File "googd0rker.py", line 42, in <module>
    google_it (site,"site:"+site+" inurl:wp- OR inurl:plugin OR inurl:upload OR inurl:download","loginpage.txt")
  File "googd0rker.py", line 34, in google_it
    for title in search(dork, stop=50):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/googlesearch/__init__.py", line 288, in search
    html = get_page(url, user_agent)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/googlesearch/__init__.py", line 154, in get_page
    response = urlopen(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```

**Comment by ZephrFish** [comment]
Hmm I'll look into it

**Comment by uday952** [comment]
Getting Too Many Requests Error

**Comment by fuomag9** [comment]
Same error, it's kinda annoying since it makes the tool useless and it doesn't even complete the search for me

**Comment by Jul10l1r4** [comment]
Running in tor network
Using `torsocks ./GoogD0rker.py -d example.com`

Can be use:
 - torsocks
 - proxychains
 - torify

If the problems persists change your node and try again

**Comment by ZephrFish** [comment]
Issue isn't with code, it is to do with rate limiting within Google
